### ISSUE TITLE
On iOS pump version number I always get .plist file not found

### ISSUE THREAD

**Issue by hannesganthaler85** [jamesmontemagno/vsts-mobile-tasks#11]
First it prints out the .plist file correctly and afterwards  on the PlistBuddy command it can not find the .plist file anymore.

logs: 

2018-02-15T09:14:58.5770190Z [command]/usr/libexec/PlistBuddy -c Print CFBundleVersion /Users/vsts/agent/2.127.0/work/4/s/Mobile Commerce RELEASE/Mobile_Commerce.iOS/Info.plist
2018-02-15T09:14:58.5798550Z File Doesn't Exist, Will Create: /Users/vsts/agent/2.127.0/work/4/s/Mobile
2018-02-15T09:14:58.5818890Z Invalid Arguments
2018-02-15T09:14:58.5826430Z 
2018-02-15T09:14:58.6065670Z [command]/usr/libexec/PlistBuddy -c Set :CFBundleVersion 1 /Users/vsts/agent/2.127.0/work/4/s/Mobile Commerce RELEASE/Mobile_Commerce.iOS/Info.plist
2018-02-15T09:14:58.6090190Z File Doesn't Exist, Will Create: /Users/vsts/agent/2.127.0/work/4/s/Mobile
2018-02-15T09:14:58.6108770Z Invalid Arguments

**Comment by jamesmontemagno** [comment]
Does the info.plist file exist there?

Mobile Commerce RELEASE/Mobile_Commerce.iOS/Info.plist

Does that look correct?  Did you pick it inside of VSTS?

**Comment by hannesganthaler85** [comment]
Yes because it gets printed out before with your task and the print option.
It is really strange that afterwards with the plist buddy command it can
not find the file anymore...

James Montemagno <notifications@github.com> schrieb am Fr. 16. Feb. 2018 um
22:24:

**Comment by jamesmontemagno** [comment]
Perhaps it is because there are spaces in the folder path.... 

Try to remove the spaces in the path perhaps?

**Comment by jamesmontemagno** [comment]
Yes this is the issue, looking into a resolution here.

**Comment by hannesganthaler85** [comment]
Thanks for the reply and nice that you found the problem.

James Montemagno <notifications@github.com> schrieb am Mo. 19. Feb. 2018 um
21:16:

**Comment by hannesganthaler85** [comment]
once I wrote my own app version pump script. It is not written in a nice way but maybe it helps you.

```
echo "Argument 1: $1"
echo "Argument2: $2"
echo "Argument3: $3"

infoPlistPath=$BUILD_SOURCESDIRECTORY"/Mobile_Commerce.iOS/$3.plist"
echo "Infoplistpath: $infoPlistPath"
oldBundleVersion=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion " $infoPlistPath)
echo "oldBundleVersion: $oldBundleVersion"

oldBundleShortVersion=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString " $infoPlistPath)
echo "oldBundleShortVersion: $oldBundleShortVersion"

PLISTBUDDY="/usr/libexec/PlistBuddy"

${PLISTBUDDY} -c "Set :CFBundleShortVersionString $1" "${infoPlistPath}";
${PLISTBUDDY} -c "Set :CFBundleVersion $2" "${infoPlistPath}";

newBundleVersion=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion " $infoPlistPath)
echo "newBundleVersion: $newBundleVersion"

newBundleShortVersion=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString " $infoPlistPath)
echo "newBundleShortVersion: $newBundleShortVersion"

```

**Comment by jamesmontemagno** [comment]
Yeah, this happened in the conversion from bash to typescript to make it a cross-platform task for VSTS.

I have the fix in place and will be publishing an update to the task in the next 24 hours. I will close this once it is live.

**Comment by hannesganthaler85** [comment]
Nice!

James Montemagno <notifications@github.com> schrieb am Di. 20. Feb. 2018 um
17:14:

**Comment by jamesmontemagno** [comment]
Pushed out 0.6.1, you may have to remove and re-add the extension. Should be fixed now.
