### ISSUE TITLE
Bundle Display Name and Application Name

### ISSUE THREAD

**Issue by dhindrik** [jamesmontemagno/vsts-mobile-tasks#12]
Thank you for creating those task for use mobile developers using VSTS! :)

I would love to have a filed in the identifier task to also set bundle display name not only bundle name on iOS and application name on Android. I will use it so it will be easier for testers that have multiple versions to select the right one when they want to test.

**Comment by jamesmontemagno** [comment]
So, this is tricky..

Android Application name is easy enough and I already do: https://developer.android.com/guide/topics/manifest/application-element.html#label

What you are thinking of is the name on the home screen, which is controlled by your StartActivity name. It isn't in the manifest traditionally in Xamarin at least. So really what you would probably want to do is use some variable switching. 

in 0.7.0 i added CFBundleDisplayName option

**Comment by dhindrik** [comment]
I missed that you had it for android! I just assumed that it worked the same way on iOS.

Thank you for adding it for iOS. :)

**Comment by jamesmontemagno** [comment]
Don't forget to rate the extension! https://marketplace.visualstudio.com/items?itemName=vs-publisher-473885.motz-mobile-buildtasks

**Comment by dhindrik** [comment]
Is this implemented in the released version? I'm can still not see Bundle Display Name in the task in my builds. Ans VSTS should auto update tasks as I have understand it.

**Comment by jamesmontemagno** [comment]
Yup! You may have to uninstall and re-install. I don't understand how VSTS does the updating.

**Comment by dhindrik** [comment]
Thanks, that worked! :)
