### ISSUE TITLE
Installed but cannot add as a task

### ISSUE THREAD

**Issue by joncortez** [jamesmontemagno/vsts-mobile-tasks#14]
Hey James! How you've been?

I am trying to use your extension and and so I requested our VSTS account admin to install it. He installed it and I can now see that it was installed when I search in the Add Task screen but it is still under Marketplace with a disabled Installed button instead of an Add button (see screenshot). Account admin already reinstalled but still issue exists. Any idea on what's going on?

![vsts-build-cannot-add-task](https://user-images.githubusercontent.com/1643951/37425950-6822e3b2-2782-11e8-8057-4e7b903fb29c.png)

**Comment by jamesmontemagno** [comment]
The task names are under iOS and Android, search for those.

**Comment by jamesmontemagno** [comment]
See: https://channel9.msdn.com/Shows/Visual-Studio-Toolbox/VSTS-for-Mobile-Development

**Comment by joncortez** [comment]
This is what happens when I don't watch your show :) Thanks and great work on the extension! This helps us generate builds for the app stores where we have to patch up the bundle identifier and package name (so we can do side by side installs of dev and app store versions).

**Comment by jamesmontemagno** [comment]
:) <3

**Comment by gabrieljoelc** [comment]
Providing a high level description of the solution here would be good 👍

**Comment by navroop163** [comment]
Advanced JTest Automation Association extension is showing installed but not showing add button to add the extension in VSTS. seethis screen shot-http://prntscr.com/lc790d

**Comment by willemodendaal** [comment]
What was the solution here?

**Comment by ruffzy** [comment]
I have the same issue with another task - what was the solution?
