### ISSUE TITLE
Rejected by VSTS admins because it doesn't comes from MS

### ISSUE THREAD

**Issue by alexrainman** [jamesmontemagno/vsts-mobile-tasks#18]
Do you believe that? What's your advice?

**Comment by ahoefling** [comment]
I personally package it up myself as a private package to use on my VSTS instance, but I am also my VSTS admin and I use a fork of this. Maybe if you created a local build of it you could get your admins buy-in to include it.

**Comment by alexrainman** [comment]
@jamesmontemagno can you release this like it comes officially from Microsoft?

**Comment by jamesmontemagno** [comment]
This is just a side project. I will bring up the discussion with the team, but I would do what @ahoefling says.

**Comment by alexrainman** [comment]
Thanks.

**Comment by alexrainman** [comment]
@jamesmontemagno any news on this?

**Comment by jamesmontemagno** [comment]
The best thing to do is to ask over on the official tasks repo: https://github.com/Microsoft/vsts-tasks
