### ISSUE TITLE
Advanced JTest Automation Association extension is showing installed but not showing add button to add the extension in VSTS. seethis screen shot-http://prntscr.com/lc790d

### ISSUE THREAD

**Issue by navroop163** [jamesmontemagno/vsts-mobile-tasks#20]
it is showing like this-
![image](https://user-images.githubusercontent.com/43744492/48045581-ecec3280-e1b6-11e8-8bd2-d15f53d8efc7.png)

**Comment by jamesmontemagno** [comment]
I see it on mine...
![image](https://user-images.githubusercontent.com/1676321/51047341-15105d00-157d-11e9-961a-c2f7ab923b34.png)
