### ISSUE TITLE
0 version code write empty string in AndroidManifest.xml

### ISSUE THREAD

**Issue by Peseur** [jamesmontemagno/vsts-mobile-tasks#21]
First thank you for your useful task. It saves a lot of time.

I noticed a 0 versionCode results in an empty string written in the AndroidManifest.xml. This causes the build to fail because empty string are not allowed for versionCode.

**Comment by jamesmontemagno** [comment]
Can you share your settings you are using and what you are seeing.... 

The before and after would be very helpful.

**Comment by Peseur** [comment]
Hello

Sure

Here are the settings

![build settings](https://user-images.githubusercontent.com/42871263/51594312-724ccc80-1ef4-11e9-9cc2-8b1e7c1b0700.png)

The Build task output
![build task output](https://user-images.githubusercontent.com/42871263/51594327-7aa50780-1ef4-11e9-97ae-0acb75b3a4f1.png)

The bump task output
![bump task output](https://user-images.githubusercontent.com/42871263/51594342-81337f00-1ef4-11e9-865c-578d9c6b3ac3.png)

Please let me know if you need further information

**Comment by jamesmontemagno** [comment]
What is your $(BuildNumber) ? It must be an integer. By default it is not.

**Comment by Peseur** [comment]
> By default it is not.
What do you mean ? BuildNumber is a pipeline variable.

**Comment by jamesmontemagno** [comment]
The default for the BuildNumber is a string, not an integer... it is like 20190123.45 or something. 

You either want to use: $(Build.BuildId) or go to your Options and change your Build Number Format to be an integer that increases :) That will fix it up.

**Comment by Peseur** [comment]
Nope. 
BuildNumber is a **custom** variable that I have defined as a Pipeline variable. There is a confusion between it and the standard Build.BuildNumber variable. BuildNumber is, in my case an **internal** build number.  
The issue persists, so.

**Comment by jamesmontemagno** [comment]
Can you print out the number somewhere? What is it set to?

**Comment by jamesmontemagno** [comment]
here is what I have:
![image](https://user-images.githubusercontent.com/1676321/51645169-de94f380-1f27-11e9-93b5-2144ce41e243.png)


Settings:
![image](https://user-images.githubusercontent.com/1676321/51645184-eeacd300-1f27-11e9-81cb-a711e7c782bd.png)


Output:
![image](https://user-images.githubusercontent.com/1676321/51645222-169c3680-1f28-11e9-88ac-4b84b6561565.png)

**Comment by Peseur** [comment]
Hi James,
I have exactly the same input/output as you excepted that I set my BuildNumber value to 0.
My build does not work but this is because a zero value is not allowed for versionCode in android. Since a 0 build number is allowed in iOS, I messed up myself. 
Nothing to do with your (awesome) task, so.
Thanks for your help and sorry for your time.

**Comment by jamesmontemagno** [comment]
no worries :0 glad you got it working
