### ISSUE TITLE
Any plan to update this repository with latest code

### ISSUE THREAD

**Issue by superjulius** [jamesmontemagno/vsts-mobile-tasks#23]
@jamesmontemagno Do you have any plan to update this repository with the latest code?

It seems that the repository corresponds to v0.8.0 of the task while published version is now 1.0.8.

I was interested in finding out how versionCode was set when using "unix timestamp" option.
I finally found this [video](https://www.youtube.com/watch?v=z5_W4LpIWME) showing you coding it :-)

**Comment by jamesmontemagno** [comment]
Yes, I need to find it! :)

**Comment by jamesmontemagno** [comment]
Found it! yay
