### ISSUE TITLE
[Android] Azure DevOps message: ##[error]unable to find the matched key.

### ISSUE THREAD

**Issue by PiotrWachulec** [jamesmontemagno/vsts-mobile-tasks#25]
Hi @jamesmontemagno :),

I'm trying to use the Bump Android Versions task, but I'm getting an error: **##[error]unable to find the matched key.**

My _AndroidManifest.xml_ looks like below:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:installLocation="auto" package="com.***" android:versionCode="1">
	<uses-sdk android:minSdkVersion="24" android:targetSdkVersion="28" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<application android:label="***.Android">
		<provider android:name="android.support.v4.content.FileProvider" android:authorities="com.***.fileprovider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
		</provider>
		<activity android:name="microsoft.identity.client.BrowserTabActivity">
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
			</intent-filter>
		</activity>
	</application>
</manifest>
```

My configuration looks like below:
![Screenshot 2019-10-10 at 09 48 02](https://user-images.githubusercontent.com/11841233/66549620-f3f88f00-eb43-11e9-80aa-b438bbe510b3.png)

And my task finished like below:
![Screenshot 2019-10-10 at 09 55 34](https://user-images.githubusercontent.com/11841233/66549701-2acea500-eb44-11e9-9318-485968c548fc.png)

Is there any my mistake or bad config?

Thanks in advance for your help!

**Comment by jamesmontemagno** [comment]
Yes, you need to add `android:versionName` This is a required attribute.

``
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.Media.Plugin.Sample">
```

**Comment by PiotrWachulec** [comment]
Works, thanks a lot!
