### ISSUE TITLE
Task add button does not appear

### ISSUE THREAD

**Issue by boletus151** [jamesmontemagno/vsts-mobile-tasks#27]
Hello,
I installed your Extension into my Company's VSTS, but there is no option to add it to a Task

![Screenshot 2020-01-10 at 07 30 55](https://user-images.githubusercontent.com/8122567/72130956-361bb180-337b-11ea-8972-6268ababe543.png)

**Comment by jamesmontemagno** [comment]
Once you add it in you can refresh that page and then search for the tasks they all have different names.

![image](https://user-images.githubusercontent.com/1676321/72186311-d4bf0700-33a9-11ea-8db4-c1d6a21552cf.png)
