### ISSUE TITLE
unable to find the matched key on iOS (Azure YAML Pipelines)

### ISSUE THREAD

**Issue by emreertugrul** [jamesmontemagno/vsts-mobile-tasks#31]
Hi, I'm using the bump version on azure devops yaml pipeline for android and ios. Same task works perfectly for android but on iOS i receive "unable to find the matched key" error. My Info.plist is 
`<key>CFBundleShortVersionString</key>
	<string>1.30.0</string>
	<key>CFBundleVersion</key>
	<string>4.0</string>
`
and i left the task to run with defaults, which is:
 (i) Version Name (shortcode): 1.0.907
 (i) Using Custom Defined Version Code and adjusting for offset if needed.
 (i) versionCodeOffset: 0
 (i) versionCode: 907

What am i missing here?

**Comment by jamesmontemagno** [comment]
Are you running this on a macOS machine? If you have logs that would be helpful too.

**Comment by emreertugrul** [comment]
Hi @jamesmontemagno , i woke up when you asked for macOS - but the issue was that I copied over the android task thinking it's the same task where it's a different task for ios - my bad, all is working well!
