### ISSUE TITLE
Getting error you are not authorized to access

### ISSUE THREAD

**Issue by dipakverma25** [jamesmontemagno/vsts-mobile-tasks#33]
![image](https://user-images.githubusercontent.com/31462675/79156867-40719f80-7df1-11ea-9b41-88abe3adb58c.png)
![image](https://user-images.githubusercontent.com/31462675/79156958-65661280-7df1-11ea-83f5-26353c82034b.png)

I am using Hosted Agent -Windows -2019
![image](https://user-images.githubusercontent.com/31462675/79157509-56339480-7df2-11ea-8357-7eb0d045713e.png)

I have tried using Username and PAT, alternate credentials and even git credentials, still no luck.
May I know is there are other setting which i am missing here.

Thanks..

**Comment by jamesmontemagno** [comment]
I don't think that this has anything to do with my extension tasks.
