### ISSUE TITLE
Commit  back to source Repo. 

### ISSUE THREAD

**Issue by aswinikailas** [jamesmontemagno/vsts-mobile-tasks#35]
Is there an option to commit back to source repo the updated changes on using this task ?

**Comment by jamesmontemagno** [comment]
You can send down a PR sure!

**Comment by aswinikailas** [comment]
Sorry I didn't understand.  Could you pls explain in detail?

**Comment by jamesmontemagno** [comment]
I guess I don't know what you are asking...

**Comment by jamesmontemagno** [comment]
Ohhhhh i see now. No there is no support for that it is just a change at runtime. You could run some git command manually though.... however I don't know if you really want your CI doing that, seems like a bad idea.
