### ISSUE TITLE
VersionCode(CFBundleVersion) iOS

### ISSUE THREAD

**Issue by dhindrik** [jamesmontemagno/vsts-mobile-tasks#9]
Why do VersionCode(CFBundleVersion) has to be an integer on iOS. There are no requirements on iOS that is has to be an integer as it is on Android.

I also suggest that you change the name in UI of the iOS task so it will match the name in info.plist.

**Comment by jamesmontemagno** [comment]
It is because I append on the offset so I do parsing there.

We could maybe make another field that is to append to the beginning.

I will update the metadata so it isn't confusing.
